-- DataBase Creation
create database customer_behavior;

-- Table Creation
CREATE TABLE customers (
    customer_id   int, age int, gender varchar(30), item_purchased varchar(50),category varchar(100), 
    purchase_amount int, location varchar(100), size varchar(100), color varchar(100), season varchar(100),
    review_rating float, subscription_status varchar(100),shipping_type varchar(100), discount_applied varchar(100),
    previous_purchases int,payment_method varchar(30),frequency_of_purchases varchar(40),age_group varchar(50), 
    purchase_frequency_days int
    
);
  
select * from customers;

-- Q1.What is the total revenue generated by Male vs Female Customers ?

select gender, sum(purchase_amount) as revenue
from customers
group by gender;

-- Q2. Which customers used a discount but still spend more than the average purchase amount?

select customer_id,purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customers);

-- Q3. which are the top 5 products with the highest average review rating ?

select top 5 item_purchased, round(avg(review_rating),2) as Average_product_rating
from customers
group by item_purchased
order by Average_product_rating desc;

-- Q4. Compare average purchase amount between standard and express shipping ?

select shipping_type, 
avg(purchase_amount)
from customers
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? company averae spent and total revenue by subscribed and non subscribed customers ?

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customers
group by subscription_status;

--Q6. Top 5 products of highest percentage of perchages with discounts applied ?
select * from customers

select top 5 item_purchased,
(sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END))*100/count(*) as discount_rate
from customers
group by item_purchased
order by discount_rate desc;

-- Q7.Segmenting the customers into New,Reterning and loyal based on 
--their total no.of previous perchases and show the Count of each segment ?

with customer_type as(
    select customer_id,previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases between 2 and 10 THEN 'Returning'
        ELSE 'Loyal'
        END as customers_segment
    from customers
   )

   select customers_segment, count(*) as 'Total_customers'
   from customer_type
   group by customers_segment;

--Q8.Top 3 Most purchased products within each catggory ?

with items as(
    select category,
    item_purchased,
    count(customer_id) as total_orders,
    ROW_Number() OVER(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased
 )

 select item_rank,category, item_purchased, total_orders
 from items
 where item_rank <= 3;

-- Q9.Which customers are repet buyers (more than 5 previous purchases) also likely to subscribe ?
select subscription_status,
count(customer_id) as repet_buyers
from customers
where previous_purchases >5
group by subscription_status;

-- Q10. what is the revenue contribution bt each age group ?
select * from customers;

select age_group,
sum(purchase_amount) as 'revenue_Contribution'
from customers
group by age_group;